// Command export-ng-schema emits a versioned, normalized snapshot of the NG
// GraphQL contract so that every client consumes ONE artifact instead of
// re-deriving the schema three independent ways (Android Apollo, StashKit
// hand-written strings, macOS forked copies).
//
// Under the NG-only decision, upstream-additivity no longer protects clients
// from server drift. This snapshot is the single source of truth the NG-to-NG
// contract test diffs against; regenerate it (make export-ng-schema) whenever
// the schema changes, and the contract test will go red until clients catch up.
//
// It loads every SDL file via gqlparser (the same parser gqlgen uses), which
// validates the multi-file schema as a whole and resolves it into a single
// deterministic AST. We then re-emit:
//
//   - ng-schema.snapshot.graphql : normalized SDL (stable ordering, no source
//     filenames, descriptions preserved) suitable for a byte-stable diff.
//   - ng-schema.introspection.json : a minimal introspection-style JSON of the
//     types/fields/args so a shell+jq harness can assert specific shapes
//     (serverCapabilities, deletedSince) without a Go toolchain.
//
// Build/run from the repo root: go run ./tools/export-ng-schema
package main

import (
	"bytes"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"sort"

	"github.com/vektah/gqlparser/v2"
	"github.com/vektah/gqlparser/v2/ast"
	"github.com/vektah/gqlparser/v2/formatter"
)

// schemaGlobs mirrors the `schema:` section of gqlgen.yml. Keep in sync with
// that file; if they drift the export would no longer reflect what the server
// actually generates against.
var schemaGlobs = []string{
	"graphql/schema/types/*.graphql",
	"graphql/schema/*.graphql",
}

const (
	sdlOut           = "graphql/schema/ng-schema.snapshot.graphql"
	introspectionOut = "graphql/schema/ng-schema.introspection.json"
	header           = "# CODE-GENERATED by tools/export-ng-schema — DO NOT EDIT BY HAND.\n" +
		"# Regenerate with `make export-ng-schema` after any schema change.\n" +
		"# This is the single NG GraphQL contract artifact every client consumes.\n\n"
)

func main() {
	if err := run(); err != nil {
		fmt.Fprintln(os.Stderr, "export-ng-schema:", err)
		os.Exit(1)
	}
}

func run() error {
	// Resolve the repo root from this file's location so the target works no
	// matter the caller's cwd (make runs it from the repo root anyway).
	root, err := os.Getwd()
	if err != nil {
		return err
	}

	sources, err := loadSources(root)
	if err != nil {
		return err
	}
	if len(sources) == 0 {
		return fmt.Errorf("no schema files matched %v under %s", schemaGlobs, root)
	}

	// LoadSchema validates the whole multi-file schema and merges it into one
	// deterministic AST — this is exactly the parse gqlgen does, so a snapshot
	// that loads here is guaranteed loadable by the server's codegen.
	schema, err := gqlparser.LoadSchema(sources...)
	if err != nil {
		return fmt.Errorf("schema failed to load (the snapshot would be invalid): %w", err)
	}

	if err := writeSDL(filepath.Join(root, sdlOut), schema); err != nil {
		return err
	}
	if err := writeIntrospection(filepath.Join(root, introspectionOut), schema); err != nil {
		return err
	}

	fmt.Printf("wrote %s\n", sdlOut)
	fmt.Printf("wrote %s\n", introspectionOut)
	return nil
}

func loadSources(root string) ([]*ast.Source, error) {
	var paths []string
	for _, glob := range schemaGlobs {
		matches, err := filepath.Glob(filepath.Join(root, glob))
		if err != nil {
			return nil, err
		}
		paths = append(paths, matches...)
	}
	// Deterministic order in case a path matches two globs; also keeps any
	// parse-error messages stable.
	sort.Strings(paths)

	// The SDL artifact lives under graphql/schema/ and so matches the globs;
	// exclude it (and any generated artifact) so the exporter never loads its
	// own prior output as an input.
	excluded := map[string]bool{
		filepath.Join(root, sdlOut): true,
	}

	seen := make(map[string]bool, len(paths))
	var sources []*ast.Source
	for _, p := range paths {
		if seen[p] || excluded[p] {
			continue
		}
		seen[p] = true
		data, err := os.ReadFile(p)
		if err != nil {
			return nil, err
		}
		rel, err := filepath.Rel(root, p)
		if err != nil {
			rel = p
		}
		sources = append(sources, &ast.Source{Name: rel, Input: string(data)})
	}
	return sources, nil
}

// writeSDL re-emits the merged schema as normalized SDL. FormatSchema produces
// a stable ordering and resolves the multi-file layout, so the output is a
// byte-stable artifact suitable for a diff-based drift check.
func writeSDL(path string, schema *ast.Schema) error {
	var buf bytes.Buffer
	buf.WriteString(header)
	f := formatter.NewFormatter(&buf)
	f.FormatSchema(schema)
	return os.WriteFile(path, buf.Bytes(), 0o644)
}

// --- minimal introspection JSON (for the shell+jq harness path) ---

type introType struct {
	Kind          string           `json:"kind"`
	Name          string           `json:"name"`
	Description   string           `json:"description,omitempty"`
	Fields        []introField     `json:"fields,omitempty"`
	InputFields   []introField     `json:"inputFields,omitempty"`
	EnumValues    []string         `json:"enumValues,omitempty"`
	PossibleTypes []string         `json:"possibleTypes,omitempty"`
	Interfaces    []string         `json:"interfaces,omitempty"`
}

type introField struct {
	Name string     `json:"name"`
	Type string     `json:"type"`
	Args []introArg `json:"args,omitempty"`
}

type introArg struct {
	Name string `json:"name"`
	Type string `json:"type"`
}

func writeIntrospection(path string, schema *ast.Schema) error {
	names := make([]string, 0, len(schema.Types))
	for name := range schema.Types {
		// Skip GraphQL built-in introspection/scalar types to keep the
		// artifact focused on the contract surface.
		if len(name) > 1 && name[0] == '_' && name[1] == '_' {
			continue
		}
		names = append(names, name)
	}
	sort.Strings(names)

	types := make([]introType, 0, len(names))
	for _, name := range names {
		def := schema.Types[name]
		t := introType{
			Kind:        string(def.Kind),
			Name:        def.Name,
			Description: def.Description,
		}
		t.Fields = convertFields(def.Fields)
		// gqlparser represents input-object fields in the same Fields list with
		// a Kind of INPUT_OBJECT, so expose them under inputFields too for a
		// caller that prefers the canonical introspection shape.
		if def.Kind == ast.InputObject {
			t.InputFields = t.Fields
			t.Fields = nil
		}
		for _, ev := range def.EnumValues {
			t.EnumValues = append(t.EnumValues, ev.Name)
		}
		for _, pt := range def.Types {
			t.PossibleTypes = append(t.PossibleTypes, pt)
		}
		t.Interfaces = append(t.Interfaces, def.Interfaces...)
		types = append(types, t)
	}

	doc := map[string]any{
		"queryType":        nameOrEmpty(schema.Query),
		"mutationType":     nameOrEmpty(schema.Mutation),
		"subscriptionType": nameOrEmpty(schema.Subscription),
		"types":            types,
	}

	out, err := json.MarshalIndent(doc, "", "  ")
	if err != nil {
		return err
	}
	out = append(out, '\n')
	return os.WriteFile(path, out, 0o644)
}

func convertFields(fields ast.FieldList) []introField {
	out := make([]introField, 0, len(fields))
	for _, fd := range fields {
		f := introField{Name: fd.Name, Type: fd.Type.String()}
		for _, a := range fd.Arguments {
			f.Args = append(f.Args, introArg{Name: a.Name, Type: a.Type.String()})
		}
		out = append(out, f)
	}
	return out
}

func nameOrEmpty(d *ast.Definition) string {
	if d == nil {
		return ""
	}
	return d.Name
}
